name: tech_taste
description: "Flutter project about Delivery."
publish_to: "humbertoromanojr.com"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  badges: ^3.1.2
  flutter:
    sdk: flutter
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banners/
    - assets/categories/
    - assets/dishes/
    - assets/others/
    - assets/restaurants/
